r"""Generate the labeled query set for query-family calibration (R-6).

Run from the repo root:
    apps\api\.venv\Scripts\python apps\api\app\engine\scripts\gen_query_pairs.py

Writes apps/api/app/engine/fixtures/query_pairs.json: 6 topics x 2 intents x 3 phrasings = 36
queries. Pair labels: same intent = "rephrase", same topic but a different question = "related",
different topic = "unrelated". The demo's own refresh-token searches are deliberately NOT in
this set, so the demo family test checks that the chosen threshold generalizes.
"""

import json
from itertools import combinations
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "fixtures" / "query_pairs.json"

TOPICS = {
    "refresh_tokens": {
        "storage": ["best place to save refresh tokens in a react app",
                    "should refresh token go in localstorage or a cookie",
                    "secure storage for jwt refresh token frontend"],
        "expiry": ["how long should a refresh token last",
                   "refresh token expiration best practice",
                   "recommended refresh token lifetime days"],
    },
    "nextjs": {
        "fs_error": ["next.js module not found can't resolve fs",
                     "cannot resolve 'fs' nextjs build error",
                     "nextjs webpack fs module not found fix"],
        "turbopack": ["how to enable turbopack in next.js 15",
                      "turn on turbopack next dev",
                      "next.js 15 use turbopack instead of webpack"],
    },
    "lisbon": {
        "sintra": ["lisbon to sintra train",
                   "how to get from lisbon to sintra",
                   "sintra day trip from lisbon by train"],
        "where_to_stay": ["best area to stay in lisbon",
                          "which lisbon neighborhood to book a hotel",
                          "alfama or baixa where to stay lisbon"],
    },
    "laptops": {
        "mac_vs_dell": ["macbook air vs dell xps for programming",
                        "dell xps 14 or macbook air 15 for developers",
                        "compare macbook air and xps for coding"],
        "battery": ["laptop with best battery life for coding",
                    "longest battery laptop for software development",
                    "programming laptop all day battery"],
    },
    "kubernetes": {
        "port_forward": ["kubectl port-forward vs nodeport",
                         "difference between port forward and nodeport service",
                         "when to use kubectl port forward instead of nodeport"],
        "restart_pod": ["how to restart a pod in kubernetes",
                        "kubectl restart pod command",
                        "force restart kubernetes pod"],
    },
    "gift": {
        "gardening_gift": ["birthday gift ideas for mom who loves gardening",
                           "gardening gifts for mother",
                           "best presents for a gardener mom"],
        "flowers": ["same day flower delivery near me",
                    "order flowers delivered today",
                    "flower delivery same day newark"],
    },
}


def main() -> None:
    queries = [{"text": q, "topic": topic, "intent": f"{topic}/{intent}"}
               for topic, intents in TOPICS.items() for intent, phrasings in intents.items() for q in phrasings]
    pairs = []
    for a, b in combinations(range(len(queries)), 2):
        qa, qb = queries[a], queries[b]
        label = ("rephrase" if qa["intent"] == qb["intent"] else
                 "related" if qa["topic"] == qb["topic"] else "unrelated")
        pairs.append({"a": a, "b": b, "label": label})
    data = {"about": "Labeled queries for R-6 query-family calibration (generated by "
                     "app/engine/scripts/gen_query_pairs.py).", "queries": queries, "pairs": pairs}
    OUT.write_bytes((json.dumps(data, indent=2, ensure_ascii=False) + "\n").encode("utf-8"))
    counts = {k: sum(p["label"] == k for p in pairs) for k in ("rephrase", "related", "unrelated")}
    print(f"wrote {OUT.name}: {len(queries)} queries, {len(pairs)} pairs {counts}")


if __name__ == "__main__":
    main()
