import { chromium } from 'playwright';
import http from 'node:http'; import os from 'node:os'; import fs from 'node:fs'; import path from 'node:path';
const EXT = path.resolve(process.env.EXT);
const results = []; const check = (n, ok, d = '') => { results.push(ok); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${d ? '  -> ' + d : ''}`); };
const sleep = ms => new Promise(r => setTimeout(r, ms));
const server = http.createServer((req, res) => { res.writeHead(200, { 'content-type': 'text/html' }); res.end(`<!doctype html><title>Page ${req.url}</title><h1>x</h1>`); });
await new Promise(r => server.listen(0, '127.0.0.1', r)); const port = server.address().port;
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tf-e2e-'));
const context = await chromium.launchPersistentContext(dir, { channel: 'chromium', headless: true, args: [`--disable-extensions-except=${EXT}`, `--load-extension=${EXT}`, '--host-resolver-rules=MAP chase.com 127.0.0.1'] });
const lines = [];
context.on('console', async m => { try { const v = await Promise.all(m.args().map(a => a.jsonValue().catch(() => null))); if (v.length === 1 && v[0] && typeof v[0] === 'object' && 'event_id' in v[0]) lines.push(v[0]); } catch {} });
let [sw] = context.serviceWorkers(); if (!sw) sw = await context.waitForEvent('serviceworker', { timeout: 15000 }); await sleep(1000);
const visit = async url => { const b = lines.length; const pg = await context.newPage(); await pg.goto(url); await sleep(1200); return { pg, types: lines.slice(b).map(l => l.type) }; };
const v1 = await visit(`http://localhost:${port}/one`);
const v2 = await visit(`http://localhost:${port}/two`);
const v3 = await visit(`http://localhost:${port}/three`);
for (const [i, v] of [[1, v1], [2, v2], [3, v3]]) console.log(`tab ${i} (blank, then navigated) event types:`, v.types.join(','));
check('every typed-URL tab (starts blank, then loads a page) gets exactly one OPEN', [v1, v2, v3].every(v => v.types.filter(t => t === 'OPEN').length === 1));
check('OPEN comes before any UPDATE for that tab', [v1, v2, v3].every(v => v.types.indexOf('OPEN') !== -1 && (v.types.indexOf('UPDATE') === -1 || v.types.indexOf('OPEN') < v.types.indexOf('UPDATE'))));
check('a FOCUS follows the OPEN of the active tab (so its BLUR has a FOCUS)', [v1, v2, v3].every(v => v.types.includes('FOCUS')));
const bank = await visit(`http://chase.com:${port}/`);
console.log('bank tab event types:', bank.types.join(',') || '(none)');
check('a banking tab still produces no OPEN, UPDATE, FOCUS or CLOSE', bank.types.every(t => t === 'BLUR'));
check('no BLUR without an earlier FOCUS for the first tab', (() => { const t = lines.map(l => l.type); const fb = t.indexOf('BLUR'), ff = t.indexOf('FOCUS'); return fb === -1 || (ff !== -1 && ff < fb); })());
check('event_ids unique', new Set(lines.map(l => l.event_id)).size === lines.length);
console.log('\nSUMMARY:', results.filter(Boolean).length, 'passed,', results.filter(x => !x).length, 'failed');
await context.close(); server.close(); fs.rmSync(dir, { recursive: true, force: true }); process.exit(results.includes(false) ? 1 : 0);
