import { chromium } from 'playwright';
import os from 'node:os'; import fs from 'node:fs'; import path from 'node:path';
const EXT = path.resolve(process.env.EXT);
const check = (n, ok, d = '') => console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${d ? '  -> ' + d : ''}`);
const sleep = ms => new Promise(r => setTimeout(r, ms));
const ctx = await chromium.launchPersistentContext(fs.mkdtempSync(path.join(os.tmpdir(), 'tf-rc-')), { channel: 'chromium', headless: true, args: [`--disable-extensions-except=${EXT}`, `--load-extension=${EXT}`] });
let [sw] = ctx.serviceWorkers(); if (!sw) sw = await ctx.waitForEvent('serviceworker', { timeout: 15000 });
await sleep(1000);
const page = await ctx.newPage(); await page.goto(`chrome-extension://${new URL(sw.url()).host}/grove.html`); await sleep(800);
await page.evaluate(() => { const b = document.createElement('button'); b.textContent = 'Restore 5 important tabs'; b.id = 'rb'; b.addEventListener('click', () => { window.__clicks = (window.__clicks || 0) + 1; window.__at = Date.now(); }); document.body.appendChild(b); window.__t0 = Date.now(); });
await page.click('#rb');
await sleep(2000);
const early = await page.evaluate(() => window.__clicks || 0);
check('the click is held while the permission question is open', early === 0, String(early));
await sleep(16000);
const late = await page.evaluate(() => ({ clicks: window.__clicks || 0, after: window.__at - window.__t0 }));
check('after 15 seconds without an answer the click goes through, once', late.clicks === 1 && late.after >= 14000 && late.after < 20000, JSON.stringify(late));
await page.click('#rb'); await sleep(500);
check('later clicks go straight through', (await page.evaluate(() => window.__clicks)) === 2);
await ctx.close();
